### ISSUE TITLE
Support for Persona 5: Royal?

### ISSUE THREAD

**Issue by tSlappy** [JFG99/CriPack#1]
Is it possible to support newer .cpk format?

![image](https://user-images.githubusercontent.com/1177940/202848137-84e0c1bb-63a1-4e6e-9fe4-59fb65114e05.png)

I can see the context of the archive, but extracting fails : Index was outside the bounds of the array.

**Comment by JFG99** [comment]
This is still very much in development.  The patching is completely unfinished and possible sections in the archive are unfinished.    I haven't had a chance to work on it in a few months.  TBH I didn't expect anyone to find it and try to use it yet.
